---
# Install apache

- name: Install Apache
  yum: name=httpd state=present

- name: Apache Service State
  service: name=httpd state=started enabled=yes

- name: Start firewalld
  service: name=firewalld state=started enabled=yes

    
- name: Add firewall rule for apache
  firewalld: port={{ httpd_port }}/tcp permanent=true state=enabled immediate=yes

