---
# This playbook contains base plays for all nodes

- name: Install base packages
  yum: "name={{ item }} state=present"
  loop: "{{ base_packages }}"

- name: Start the firewalld service
  service: name=firewalld state=started enabled=yes

- name: Add users
  user:
    name: "{{ item.name }}"
    state: present
    groups: "{{ item.groups }}"
  loop:
    - { name: 'webadmin1', groups: 'wheel' }
    - { name: 'webadmin2', groups: 'apache' }

